export enum WorkerStatus{
   ONLINE = 'ONLINE',
   OFFLINE = 'OFFLINE',
   BLOCKED = 'BLOCKED',
   IN_SERVICE = 'IN_SERVICE',
   WAITING_DOCUMENTS = 'WAITING_DOCUMENTS',
   PENDING_APPROVAL = 'PENDING_APPROVAL',
   REJECTED = 'REJECTED'
}