export enum BookingStatus {
    REQUESTED = "REQUESTED",
    WORKER_ACCEPTED = "WORKER_ACCEPTED",
    WORKER_CANCELLED = "WORKER_CANCELLED",
    CUSTOMER_CANCELLED = "CUSTOMER_CANCELLED",
    IN_PROGRESS = "IN_PROGRESS",
    WORK_COMPLETED_PENDING = "WORK_COMPLETED_PENDING", // Worker completed, awaiting customer confirmation
    COMPLETED = "COMPLETED",
    INVOICE_GENERATED = "INVOICE_GENERATED",
    PAYMENT_PENDING = "PAYMENT_PENDING",
    PAID = "PAID",
    WORKER_REJECTED = "WORKER_REJECTED",
    CUSTOMER_REJECTED = "CUSTOMER_REJECTED"
}