export enum BookingStatus {
    REQUESTED = "REQUESTED",
    WORKER_ACCEPTED = "WORKER_ACCEPTED",
    WORKER_CANCELLED = "WORKER_CANCELLED",
    CUSTOMER_CANCELLED = "CUSTOMER_CANCELLED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    WORKER_REJECTED = "WORKER_REJECTED",
    CUSTOMER_REJECTED = "CUSTOMER_REJECTED"
}